# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'last.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 801)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.central_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_bottom = QtWidgets.QLabel(self.central_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_bottom.setFont(font)
        self.label_bottom.setObjectName("label_bottom")
        self.gridLayout.addWidget(self.label_bottom, 0, 0, 1, 1)
        self.back_button = QtWidgets.QPushButton(self.central_widget)
        self.back_button.setMinimumSize(QtCore.QSize(112, 44))
        self.back_button.setMaximumSize(QtCore.QSize(112, 44))
        self.back_button.setStyleSheet("QPushButton {\n"
"background-color: rgb(150, 176, 203);\n"
"color: rgb(255, 255, 255);\n"
"border-radius : 22;\n"
"border-bottom : 2px solid rgb(140, 165, 189);\n"
"border-right: 2px solid rgb(140, 165, 189);\n"
"}\n"
"QPushButton::hover {\n"
"background-color: rgb(140, 165, 189);\n"
"color: rgb(255, 255, 255);\n"
"border-radius : 22;\n"
"}")
        self.back_button.setObjectName("back_button")
        self.gridLayout.addWidget(self.back_button, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.save_button = QtWidgets.QPushButton(self.central_widget)
        self.save_button.setMinimumSize(QtCore.QSize(112, 44))
        self.save_button.setMaximumSize(QtCore.QSize(112, 44))
        self.save_button.setStyleSheet("QPushButton {\n"
"background-color: #389CD8;\n"
"color: rgb(255, 255, 255);\n"
"border-radius : 22;\n"
"border-bottom : 2px solid #2E93CF;\n"
"border-right: 2px solid #2E93CF;\n"
"}\n"
"QPushButton::hover {\n"
"background-color: #2E93CF;\n"
"color: rgb(255, 255, 255);\n"
"border-radius : 22;\n"
"}")
        self.save_button.setObjectName("save_button")
        self.gridLayout.addWidget(self.save_button, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 6)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_title = QtWidgets.QLabel(self.central_widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("background-color: rgb(135, 198, 212);\n"
"color: rgb(30, 72, 154);")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout_3.addWidget(self.label_title, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 3, 1, 1)
        self.table_view = QtWidgets.QTableView(self.central_widget)
        self.table_view.setMinimumSize(QtCore.QSize(400, 0))
        self.table_view.setMaximumSize(QtCore.QSize(400, 16777215))
        self.table_view.setStyleSheet("background-color: rgb(243, 234, 227);\n"
"alternate-background-color: rgb(225, 216, 209);")
        self.table_view.setObjectName("table_view")
        self.gridLayout_3.addWidget(self.table_view, 1, 2, 1, 1)
        self.vertical_layout_3 = QtWidgets.QVBoxLayout()
        self.vertical_layout_3.setObjectName("vertical_layout_3")
        self.label_1 = QtWidgets.QLabel(self.central_widget)
        self.label_1.setObjectName("label_1")
        self.vertical_layout_3.addWidget(self.label_1)
        self.label_2 = QtWidgets.QLabel(self.central_widget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.vertical_layout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.central_widget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.vertical_layout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.central_widget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.vertical_layout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.central_widget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.vertical_layout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.central_widget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.vertical_layout_3.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.central_widget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.vertical_layout_3.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.central_widget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.vertical_layout_3.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.central_widget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.vertical_layout_3.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.central_widget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.vertical_layout_3.addWidget(self.label_10)
        self.gridLayout_3.addLayout(self.vertical_layout_3, 1, 1, 1, 1)
        self.vertical_layout_text = QtWidgets.QVBoxLayout()
        self.vertical_layout_text.setObjectName("vertical_layout_text")
        self.label_cong = QtWidgets.QLabel(self.central_widget)
        self.label_cong.setMinimumSize(QtCore.QSize(0, 40))
        self.label_cong.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_cong.setFont(font)
        self.label_cong.setStyleSheet("color: rgb(30, 72, 154);\n"
"")
        self.label_cong.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cong.setObjectName("label_cong")
        self.vertical_layout_text.addWidget(self.label_cong)
        self.label_having = QtWidgets.QLabel(self.central_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_having.setFont(font)
        self.label_having.setStyleSheet("color: rgb(30, 72, 154);")
        self.label_having.setAlignment(QtCore.Qt.AlignCenter)
        self.label_having.setObjectName("label_having")
        self.vertical_layout_text.addWidget(self.label_having)
        self.label_blue = QtWidgets.QLabel(self.central_widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_blue.setFont(font)
        self.label_blue.setStyleSheet("background-color: rgb(56, 156, 216);\n"
"color: rgb(255, 255, 255);\n"
"border-radius : 16;")
        self.label_blue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_blue.setIndent(-1)
        self.label_blue.setObjectName("label_blue")
        self.vertical_layout_text.addWidget(self.label_blue)
        self.label_take = QtWidgets.QLabel(self.central_widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_take.setFont(font)
        self.label_take.setStyleSheet("color: rgb(30, 72, 154);")
        self.label_take.setAlignment(QtCore.Qt.AlignCenter)
        self.label_take.setObjectName("label_take")
        self.vertical_layout_text.addWidget(self.label_take)
        self.gridLayout_3.addLayout(self.vertical_layout_text, 0, 4, 2, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 6)
        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_bottom.setText(_translate("MainWindow", "You can save your results so that you can resee them later."))
        self.back_button.setText(_translate("MainWindow", "back"))
        self.save_button.setText(_translate("MainWindow", "save"))
        self.label_title.setText(_translate("MainWindow", "MY TOP VALUES"))
        self.label_1.setText(_translate("MainWindow", "1"))
        self.label_2.setText(_translate("MainWindow", "2"))
        self.label_3.setText(_translate("MainWindow", "3"))
        self.label_4.setText(_translate("MainWindow", "4"))
        self.label_5.setText(_translate("MainWindow", "5"))
        self.label_6.setText(_translate("MainWindow", "6"))
        self.label_7.setText(_translate("MainWindow", "7"))
        self.label_8.setText(_translate("MainWindow", "8"))
        self.label_9.setText(_translate("MainWindow", "9"))
        self.label_10.setText(_translate("MainWindow", "10"))
        self.label_cong.setText(_translate("MainWindow", "Congratulations!"))
        self.label_having.setText(_translate("MainWindow", "Having this exercise completed, you now have your\n"
" top 5 values listed in order of priority. Great job!\n"
"\n"
"One last thing to do is to ask yourself:"))
        self.label_blue.setText(_translate("MainWindow", "• Do I live up to my own values?\n"
"\n"
"• How are these values\n"
"represented in my current state\n"
"of life?\n"
"\n"
"• How do I implement them into\n"
"my life so that I’m happier?"))
        self.label_take.setText(_translate("MainWindow", "Take your time to think."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
